### ISSUE TITLE
An exception occurred during a WebClient request.. Retrying in one second...

### ISSUE THREAD

**Issue by katdti** [eli-ba/nusave#4]
Using Version 1.0.?
I Downloaded 1.0.1 package but "nusave version" command returns "1.0.0+4085"

To reproduce:
   `NuSave -id "CommonServiceLocator" -version "1.3.0" -outputDirectory "C:\Temp\Nuget"`
Result:
   Never ending logs:    
>   An exception occurred during a WebClient request.. Retrying in one second...
>   An exception occurred during a WebClient request.. Retrying in one second...
>...

This does not produce the error:
   `NuSave -id "CommonServiceLocator" -version "2.0.4" -outputDirectory "C:\Temp\Nuget"`

**Comment by kkukshtel** [comment]
Getting the same issue here for packages. Tried it for Microsoft.CodeAnalysis.Analyzers 3.3.0.

**Comment by eli-ba** [comment]
Issue fixed in release 2.0.0. Could you please confirm that it's working now?

**Comment by katdti** [comment]
Although downloading CommonServiceLocator 2.0.4 seems to download all the internet because nusave downloads all platforms - I can confirm version 2.0.0 solves the problem described in this issue. Closing issue.

**Comment by eli-ba** [comment]
@katdti I just release version 3.0.0 which adds the ability to filter specific platforms.

Example:
`nusave cache package "Newtonsoft.Json@12.0.3" --targetFrameworks ".NETStandard@1.0,.NETStandard@1.3" --cacheDir "C:\path\to\my-local-feed"`

That way we don't have to download the whole internet 😅

I did some tests on my side, I would be glad if you could also give it a try and let me know if that works as intended.

**Comment by katdti** [comment]
>I would be glad if you could also give it a try and let me know if that works as intended.

It depends.

This command crashes if no other package has been downloaded previous:
`NuSave cache package "CommonServiceLocator@2.0.4" --targetFrameworks ".NETStandard@1.0,.NETFramework@4.5,.NETCoreApp"  --cacheDir "C:\Temp\Nuget"
`

and I would expect  below commands to download the same content on an **empty** cacheDir - but they don't:

`NuSave cache package "CommonServiceLocator@2.0.4"  --cacheDir "C:\Temp\Nuget"
`

`NuSave cache package "CommonServiceLocator@2.0.4" --targetFrameworks ".NETStandard@,.NETFramework@,.NETCoreApp@"  --cacheDir "C:\Temp\Nuget"`

**Comment by eli-ba** [comment]
@katdti It's crashing because the commands are specifying the target framework `.NETCoreApp` without version.
Try this:
```
NuSave cache package "CommonServiceLocator@2.0.4" --targetFrameworks ".NETStandard@1.0,.NETFramework@4.5,.NETCoreApp@1.0" --cacheDir "C:\Temp\Nuget"
```

**Comment by katdti** [comment]
OK.
