### ISSUE TITLE
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.    at NuSave.Core.DependencyResolver.Append(IPackageSearchMetadata package)

### ISSUE THREAD

**Issue by David-Moreira** [eli-ba/nusave#7]
Getting this on a NET5 WEB API:
I ran:
nusave cache sln "C:\Users\P058455\source\repos\odoc\ODOC.Template.sln" --cacheDir "C:\Desktop\ODOC"
Can you help me troubleshoot?

![image](https://user-images.githubusercontent.com/22283161/111359603-a01c9e80-8683-11eb-99e7-1854e77cd29b.png)

**Comment by eli-ba** [comment]
Could you please share with me your `.sln` and `.csproj` files? That way I can reproduce the issue. Thanks.

**Comment by Chaosbit** [comment]
Hi,
I have the same problem. Seems like it comes from the fact that we are using an additional repository and the package is not found.

![image](https://user-images.githubusercontent.com/55083/115355455-fc129f80-a1ba-11eb-9cac-9f3cb57198a6.png)

**Comment by David-Moreira** [comment]
Hello,
I'm sorry for not replying back... Just too busy on other stuff, and ended up going with a different solution.
I do have other nuget sources, yes.

**Comment by sikri-eic** [comment]
I experienced the same problem and I also have external NuGet sources. I think reading the nuget.config file could be a solution for this kind of problems.

@David-Moreira What other solution did you use? I don't want to copy the whole nuget cache from another machine...

**Comment by David-Moreira** [comment]
Yea I ended up with a similar solution. Altough I don't think the dotnet restore command was doing exactly what I wanted it to do. I wanted every single sln nuget package dependecy, and I don't think I was getting everything... I don't quite recall now.

Eitherway, What I personally did, I just cleared the nuget cache, restored and used my global nuget folder as an input folder to export the packages to where I wanted to export them.

**Comment by eli-ba** [comment]
I just implemented support for multiple sources.

Release: https://github.com/eli-ba/nusave/releases/tag/v3.1.0
Issue: #8 
Commit: https://github.com/eli-ba/nusave/commit/991d7210ef1666e5c75a649c204d0ba7d5ff604f

Additional sources will be automatically read from .csproj using `<RestoreAdditionalProjectSources/>` and `<RestoreSources/>`:
```xml
<RestoreAdditionalProjectSources>
  https://api.nuget.org/v3/index.json;
  https://www.myget.org/F/sixlabors/api/v3/index.json;
</RestoreAdditionalProjectSources>
```
```xml
<RestoreSources>
  https://api.nuget.org/v3/index.json;
  https://www.myget.org/F/sixlabors/api/v3/index.json;
</RestoreSources>
```

Or via the command line's `--sources` option, which accepts comma separated URLs.

I will close this issue for now, please let me know if something is not working.

**Comment by eli-ba** [comment]
@David-Moreira let me know if that works for you.

**Comment by sikri-eic** [comment]
@eli-ba I haven't tested it, but briefly looking at the code, this solution does not support password protected sources. That may be one thing users of `nusave` may need.

**Comment by David-Moreira** [comment]
Yea. Mine do have password. Also seems like a bother to be duplicating configuration. Is it not possible to read the current configuration as it would be expected?

**Comment by eli-ba** [comment]
@David-Moreira it's not required to duplicate the configuration. I just show in the example that we support both `<RestoreAdditionalProjectSources/>` and `<RestoreSources/>`, adding one of them should be enough.

@sikri-eic we could look into password protected sources, btw pull requests are welcome :)

**Comment by David-Moreira** [comment]
What about package.config file?

**Comment by eli-ba** [comment]
> What about package.config file?

I created two issues:
- #10 Support package.config
- #9 Support password protected NuGet sources

I will be happy to merge your pull requests.

**Comment by David-Moreira** [comment]
Haha I'll let you know if I have time...
